
version: 2

# Changing working with sources (currently using 'ref' keyword)
# sources:
#   - name: dbt-demo-db
#     schema: dbt_demo_db
#     tables:
#       - name: customers
#       - name: order_items
#       - name: orders
#       - name: products
#       - name: web_events

models:
  - name: stg_customers
    description: "Cleaning customers data"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - id_correct_format:
              column_name: customer_id
      - name: customer_name
        description: "customer first name"
        tests:
          - not_null
      - name: customer_email
        description: "customer email"
        tests:
          - not_null
          - unique
      - name: customer_address
        description: "customer adress"
        tests:
          - not_null
      - name: registration_date
        description: "customer registration date"
        tests:
          - not_null
      - name: customer_segment
        description: "customer segment"
        tests:
          - not_null