
version: 2

# Changing  sources for reference (currently using 'ref' keyword)
# sources:
#   - name: dbt-demo-db
#     schema: dbt_demo_db
#     tables:
#       - name: customers
#       - name: order_items
#       - name: orders
#       - name: products
#       - name: web_events

models:
  - name: stg_customers
    description: "Cleaning customers data"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
          - id_correct_format:
              column_name: customer_id
          - dbt_utils.not_empty_string
      - name: customer_name
        description: "customer first name"
        tests:
          - not_null
      - name: customer_email
        description: "customer email"
        tests:
          - not_null
          - unique
      - name: customer_address
        description: "customer adress"
        tests:
          - not_null
      - name: registration_date
        description: "customer registration date"
        tests:
          - not_null
          - date_later_than_today:
              column_name: registration_date
      - name: customer_segment
        description: "customer segment"
        tests:
          - not_null
          - accepted_values:
              values: ['A', 'B', 'C']
  - name: stg_products
    columns:
      - name: product_id
        description: "product primary key"
        tests:
          - not_null
      - name: product_name
        description: "product name"
        tests:
          - not_null
      - name: product_description
        description: "product description"
        tests:
          - not_null
      - name: product_category
        description: "product category"
        tests:
          - not_null
          - accepted_values:
              values: ['Apparel','Home Goods','Books','Electronics', 'No category']
      - name: product_price
        description: "product price"
        tests:
          - not_null
          - value_less_than_zero:
              column_name: product_price
      - name: product_sku
        description: "product sku"
        tests:
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        description: "order primary key"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "customer id foreing key" 
        tests:
          - not_null
          - id_correct_format:
              column_name: customer_id
          - relationships: 
              to: ref('stg_customers')
              field: customer_id
              config:
                severity: warn
      - name: order_date
        description: "order date"
        tests:
          - not_null
          - date_later_than_today:
              column_name: order_date
      - name: order_status
        description: "order status"
        tests:
          - not_null
          - accepted_values:
              values: ['SHIPPED', 'PENDING','DELIVERED','PROCESSING','CANCELLED']
      - name: payment_method
        description: "payment method"
        tests:
          - not_null
          - accepted_values:
              values: ['Credit Card','PayPal','Bank Transfer']
  - name: stg_order_items
    columns:
      - name: order_id
        description: "order id foreing key"
        tests:
          - not_null
      - name: product_id
        description: "product id foreing key" 
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
              config: 
                severity: warn
      - name: quantity
        description: "order item quantity"
        tests:
          - not_null
          - value_less_than_zero:
              column_name: quantity
      - name: unit_price
        description: "order item unit price"
        tests:
          - not_null
          - value_less_than_zero:
              column_name: quantity
      - name: discount
        description: "order item discount"
        tests:
          - not_null
          - value_less_than_zero:
              column_name: quantity
  - name: stg_web_events
    columns:
      - name: web_session_id
        description: "web session id"
        tests:
          - not_null
      - name: customer_id
        description: "session customer id" 
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
              config:
                severity: warn
      - name: web_session_date
        description: "web session date"
        tests:
          - not_null
          - date_later_than_today:
              column_name: web_session_date
      - name: web_event_type
        description: "web event type"
        tests:
          - not_null
      - name: web_url
        description: "web url"
        tests:
          - not_null
  - name: dim_customers
    columns:
      - name: customer_id
        description: "customer id"
        tests:
          - not_null
          - unique
          - id_correct_format:
              column_name: customer_id
      - name: customer_name
        description: "customer name" 
        tests:
          - not_null
      - name: customer_email
        description: "customer email"
        tests:
          - not_null
      - name: customer_address
        description: "customer address"
        tests:
          - not_null
      - name: registration_date
        description: "registration date"
        tests:
          - not_null
          - date_later_than_today:
              column_name: registration_date
      - name: customer_segment
        description: "customer segment"
        tests:
          - not_null
          - accepted_values:
              values: ['A', 'B', 'C']
      - name: load_timestamp
        description: "load timestamp"
        tests:
          - not_null
  - name: dim_products
    columns:
      - name: product_id
        description: "product id"
        tests:
          - not_null
      - name: product_name
        description: "product name" 
        tests:
          - not_null
      - name: product_description
        description: "product description"
        tests:
          - not_null
      - name: product_category
        description: "product category"
        tests:
          - not_null
      - name: product_price
        description: "product price "
        tests:
          - not_null
      - name: product_sku
        description: "product sku"
        tests:
          - not_null
      - name: load_date
        description: "load date"
        tests:
          - not_null
  - name: fct_orders
    columns:
      - name: order_id
        description: "order id"
        tests:
          - not_null
      - name: customer_id
        description: "customer id " 
        tests:
          - not_null
      - name: product_id
        description: "product id"
        tests:
          - not_null
      - name: quantity
        description: "quantity"
        tests:
          - not_null
      - name: total_amout
        description: "total amout"
        tests:
          - not_null
      - name: order_date
        description: "order date"
        tests:
          - not_null
      - name: order_status
        description: "order status"
        tests:
          - not_null
      - name: payment_method
        description: "payment method"
        tests:
          - not_null
      - name: load_date
        description: "load date"
        tests:
          - not_null
  - name: agg_sales_by_year
    columns:
      - name: total_number_of_orders
        description: "total number of orders"
        tests:
          - not_null
      - name: total_sales_by_year
        description: "total sales by year" 
        tests:
          - not_null
      - name: year
        description: "year value"
        tests:
          - not_null
      - name: number_of_total_unique_customers
        description: "number of total unique customers"
        tests:
          - not_null
      - name: number_of_total_customers
        description: "number of total customers"
        tests:
          - not_null