
version: 2

# Changing working with sources (currently using 'ref' keyword)
# sources:
#   - name: dbt-demo-db
#     schema: dbt_demo_db
#     tables:
#       - name: customers
#       - name: order_items
#       - name: orders
#       - name: products
#       - name: web_events

models:
  - name: stg_customers
    description: "Cleaning customers data"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - id_correct_format:
              column_name: customer_id
      - name: customer_name
        description: "customer first name"
        tests:
          - not_null
      - name: customer_email
        description: "customer email"
        tests:
          - not_null
          - unique
      - name: customer_address
        description: "customer adress"
        tests:
          - not_null
      - name: registration_date
        description: "customer registration date"
        tests:
          - not_null
      - name: customer_segment
        description: "customer segment"
        tests:
          - not_null
  - name: stg_products
    columns:
      - name: product_id
        description: "product primary key"
        tests:
          - not_null
      - name: product_name
        description: "product name"
        tests:
          - not_null
      - name: product_description
        description: "product description"
        tests:
          - not_null
      - name: product_category
        description: "product category"
        tests:
          - not_null
      - name: product_price
        description: "product price"
        tests:
          - not_null
          - value_less_than_zero:
              column_name: product_price
      - name: product_sku
        description: "product sku"
        tests:
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        description: "order primary key"
        tests:
          - not_null
      - name: customer_id
        description: "customer id foreing key" 
        tests:
          - not_null
      - name: order_date
        description: "order date"
        tests:
          - not_null
          - date_later_than_today:
              column_name: order_date
      - name: order_status
        description: "order status"
        tests:
          - not_null
      - name: payment_method
        description: "payment method"
        tests:
          - not_null